version: "3"
services:
  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example123
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=mixiphp
      - MYSQL_PASSWORD=example123
    volumes:
      - "data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - default
  server:
    container_name: mixiphp
    image: ldcmleo1360/mixiphp
    restart: always
    links:
      - db
    volumes:
      - "C:/Users/leonardo/Public/mixiphp/src/public:/var/www/html"
      - "C:/Users/leonardo/Public/mixiphp/src/app:/var/www/app"
    ports:
      - "80:80"
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
       - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: mixiphp
      MYSQL_PASSWORD: example123
      MYSQL_ROOT_PASSWORD: example123 
volumes:
  data: